project:
  type: website
  output-dir: _site
  
website:
  title: "GeckoSec"
  navbar:
    logo: images/logo.png
    # logo-href: https://Riley-Raasch.github.io/
    right:
      - icon: twitter
        href: https://twitter.com/Pratikpkb
      - icon: linkedin
        href: https://www.linkedin.com/in/riley-raasch-b79178220/
      - icon: github
        href: https://github.com/Riley-Raasch
    left: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
  favicon: images/logo.png
  twitter-card: true
  comments: false
  # google-analytics:
  # body-header:
  # body-footer:

format:
  html:
    theme: cosmo #darkly #pulse #skectchy #superhero 
    css: styles.css
  
